name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build Everything
        run: |
          # Automatically find the frontend folder
          PROJECT_DIR=$(dirname $(find . -name "capacitor.config.json" | head -n 1))
          cd $PROJECT_DIR
          
          # Install and build web app
          npm install
          npm run build
          npx cap sync android
          
          # Build Android APK
          cd android
          chmod +x ./gradlew
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: DeliveryTrackerApp
          path: '**/android/app/build/outputs/apk/debug/app-debug.apk'
